apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu01
  name: ubuntu01
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu01
  strategy: {}
  template:
    metadata:
      labels:
        app: ubuntu01
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 100; done"
        volumeMounts:
          - name: db-config
            mountPath: /tmp
            readOnly: true
      volumes:
      - name: db-config
        configMap:
          name: db-config

