apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: box0
  name: box0
spec:
  containers:
  - args:
    - '/bin/sh'
    - '-c'
    - 'sleep 15'
    - 'touch /tmp/debug'
    - 'sleep 15'
    - 'rm /tmp/debug'
    image: busybox
    name: box0
    livenessProbe:
      exec:
        command:
        - '/bin/sh'
        - '-c'
        - 'test -f /tmp/debug && echo "file exists" '
      initialDelaySeconds: 20
      periodSeconds: 20
