apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx03
  name: nginx03
spec:
  containers:
  - image: nginx
    name: nginx03
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
