apiVersion: v1
kind: PersistentVolume
metadata:
  name: deploy-history
  labels:
    tier: middleware
    audit: "true"
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/deployment"
