apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu03
  name: ubuntu03
spec:
  containers:
  - image: ubuntu
    name: ubuntu03
    command:
    - '/bin/sh'
    - '-c'
    - 'while true; do sleep 10; done'
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
