apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx02
  name: nginx02
spec:
  containers:
  - image: nginx:alpine
    name: nginx02
    resources: {}
  tolerations:
  - key: "mode"
    value: "maintenance"
    #operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
    app: web
