apiVersion: v1
kind: Pod
metadata:
    name: multi-container-pod
spec:
    containers:
        - name: web
          image: nginx
        - name: db
          image: couchbase
        - name: cache
          image: redis
