apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
    - name: nginx
      image: nginx
  initContainers:
    - name: init-delay
      image: busybox
      command: ['sleep','30']
