apiVersion: v1
kind: Pod
metadata:
    name: configmap-volume-reader
spec:
    containers:
        - name: busybox
          image: busybox
          command: ['sh','-c','while true; do sleep 3600; done']
          volumeMounts: 
            - name: configmap-volume
              mountPath: /etc/config/configmap
    volumes:
        - name: configmap-volume
          configMap: 
            name: sample-configmap
