apiVersion: v1
kind: Pod
metadata: 
    name: readconfigmap-pod
spec:
    containers: 
    - name: busybox
      image: busybox
      command: ['sh','-c','echo "$CONFIGMAPVAR from configmap"']
      env:
          - name: CONFIGMAPVAR
            valueFrom: 
                configMapKeyRef:
                    name: sample-configmap
                    key: message
