apiVersion: v1
kind: Pod
metadata: 
    name: big-request-pod
spec:
    containers:
        - name: busybox
          image: busybox
          command: ['sh','-s','while true; do sleep 3600; done']
          resources:
              requests: 
                # use 10 cpus
                cpu: "10000m"
                memory: "128Mi"
