apiVersion: v1
kind: Pod
metadata: 
    name: readsecret-pod
spec:
    containers: 
    - name: busybox
      image: busybox
      command: ['sh','-c','echo "$MYSECRET from secret"']
      env:
          - name: MYSECRET
            valueFrom: 
                secretKeyRef:
                    name: my-secret
                    key: passphase
