apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  containers: 
    - name: busybox-1
      image: busybox
      volumeMounts: 
        - name: shared-volume
          mountPath: /input
    - name: busybox-2
      image: busybox
      volumeMounts: 
        - name: shared-volume
          mountPath: /output

