apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cron-hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ['sh','-c','date; echo Hello from Cluster!']
          restartPolicy: OnFailure
