apiVersion: v1
kind: Pod
metadata:
    name: sidecar-pod
spec:
    containers:
        - name: logger
          image: busybox
          command: ['sh','-c','while true; do echo logs data > /output/log.txt; sleep 5; done']
          volumeMounts:
              - name: logvolume
                mountPath: /output
        - name: reader
          image: busybox
          command: ['sh','-c', 'tail -f /input/log.txt']
          volumeMounts:
              - name: logvolume
                mountPath: /input
    volumes:
        - name: logvolume
          emptyDir: {}
