apiVersion: v1
kind: Pod
metadata: 
    name: http-pod-with-resources
spec:
    containers: 
        - name: nginx
          image: nginx:1.19.1
          resources:
               requests:
                   cpu: "250m"
                   memory: "128Mi"
               limits: 
                   cpu: "500m"
                   memory: "256Mi"
