apiVersion: v1
kind: Pod
metadata:
    name: secrets-volume-reader
spec:
    containers:
        - name: busybox
          image: busybox
          command: ['sh','-c','while true; do sleep 3600; done']
          volumeMounts: 
            - name: secrets-volume
              mountPath: /etc/config/secrets
    volumes:
        - name: secrets-volume
          secret: 
            secretName: my-secret
